export const seedClients = [
  {
    id: 101,
    name: "Van Colombia",
    customerType: "Empresa",
    visual: "empresa",
    need: "Asegurar flota corporativa",
    context:
      "La empresa acaba de ampliar su operación y necesita asegurar 12 vehículos de distribución urbana.",
    line: "Autos",
    premium: 120,
    claims: 38,
    commission: 12,
    risk: "Medio",
    tag: "Alta oportunidad",
  },
  {
    id: 102,
    name: "Carlos Ramírez",
    customerType: "Persona natural",
    visual: "hombre",
    need: "Asegurar vehículo particular",
    context:
      "Va a comprar un Mazda 2 modelo 2024 y busca cobertura para uso diario en Bogotá.",
    line: "Autos",
    premium: 4.2,
    claims: 1.1,
    commission: 0.42,
    risk: "Bajo",
    tag: "Cierre rápido",
  },
  {
    id: 103,
    name: "Constructora Horizonte",
    customerType: "Empresa",
    visual: "empresa",
    need: "Garantías para contratos",
    context:
      "Necesita respaldo para participar en nuevos procesos contractuales durante el trimestre.",
    line: "Fianzas",
    premium: 180,
    claims: 20,
    commission: 16,
    risk: "Bajo",
    tag: "Cliente estratégico",
  },
  {
    id: 104,
    name: "Grupo Vital",
    customerType: "Empresa",
    visual: "empresa",
    need: "Cobertura de vida colectiva",
    context: "Busca una solución para su equipo directivo y personal clave.",
    line: "Vida",
    premium: 90,
    claims: 25,
    commission: 9,
    risk: "Medio",
    tag: "Alta retención",
  },
  {
    id: 105,
    name: "Logística Nova",
    customerType: "Empresa",
    visual: "empresa",
    need: "Renovar pólizas de vehículos y carga",
    context:
      "Viene de una mala experiencia con su aseguradora actual, pero tiene siniestralidad presionada.",
    line: "Generales",
    premium: 140,
    claims: 62,
    commission: 14,
    risk: "Alto",
    tag: "Riesgo alto",
  },
  {
    id: 106,
    name: "Mónica Londoño",
    customerType: "Persona natural",
    visual: "mujer",
    need: "Proteger vehículo y hogar",
    context:
      "Busca agrupar seguros con una sola compañía si le ofrecen buena atención.",
    line: "Generales",
    premium: 8.5,
    claims: 2.3,
    commission: 0.85,
    risk: "Bajo",
    tag: "Cross-sell",
  },
  {
    id: 107,
    name: "Red Médica Integral",
    customerType: "Empresa",
    visual: "empresa",
    need: "Cobertura de vida y patrimoniales",
    context:
      "Busca una solución integral y valora mucho el acompañamiento técnico.",
    line: "Vida",
    premium: 130,
    claims: 34,
    commission: 13,
    risk: "Medio",
    tag: "Cliente valioso",
  },
  {
    id: 108,
    name: "Agroinsumos del Centro",
    customerType: "Empresa",
    visual: "empresa",
    need: "Póliza patrimonial",
    context:
      "Quiere asegurar inventario y operación, pero todavía está comparando propuestas.",
    line: "Generales",
    premium: 72,
    claims: 21,
    commission: 7,
    risk: "Medio",
    tag: "Oportunidad media",
  },
  {
    id: 109,
    name: "María José Díaz",
    customerType: "Persona natural",
    visual: "mujer",
    need: "Seguro de vida individual",
    context:
      "Está organizando sus finanzas y quiere proteger a su familia.",
    line: "Vida",
    premium: 5.8,
    claims: 1.4,
    commission: 0.58,
    risk: "Bajo",
    tag: "Rentable",
  },
  {
    id: 110,
    name: "TecnoMarket SAS",
    customerType: "Empresa",
    visual: "empresa",
    need: "Cumplimiento y manejo",
    context:
      "Requiere una respuesta rápida para cerrar un negocio en menos de una semana.",
    line: "Fianzas",
    premium: 110,
    claims: 15,
    commission: 10,
    risk: "Bajo",
    tag: "Urgente",
  },
  {
    id: 111,
    name: "MoviExpress",
    customerType: "Empresa",
    visual: "empresa",
    need: "Póliza de flota mixta",
    context:
      "Tiene alto movimiento operativo y antecedentes de reclamaciones recientes.",
    line: "Autos",
    premium: 155,
    claims: 74,
    commission: 15,
    risk: "Alto",
    tag: "Cliente complejo",
  },
  {
    id: 112,
    name: "Isabela Cárdenas",
    customerType: "Persona natural",
    visual: "mujer",
    need: "Asegurar su primer carro",
    context:
      "Busca respaldo, facilidad y una experiencia sencilla de compra.",
    line: "Autos",
    premium: 3.9,
    claims: 1.0,
    commission: 0.39,
    risk: "Bajo",
    tag: "Fácil de cerrar",
  },
  {
    id: 113,
    name: "Felipe Torres",
    customerType: "Persona natural",
    visual: "hombre",
    need: "Seguro de vida y accidentes",
    context:
      "Quiere proteger a su familia y busca una cobertura sencilla con buen respaldo.",
    line: "Vida",
    premium: 6.2,
    claims: 1.8,
    commission: 0.62,
    risk: "Bajo",
    tag: "Persona natural",
  },
  {
    id: 114,
    name: "Distribuciones Andina SAS",
    customerType: "Empresa",
    visual: "empresa",
    need: "Póliza patrimonial y transporte",
    context:
      "Necesita asegurar inventario y mercancía por expansión de operaciones.",
    line: "Generales",
    premium: 160,
    claims: 40,
    commission: 15,
    risk: "Medio",
    tag: "Empresa clave",
  },
];